# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  desc “Build, and push a release to AppCenter”
  lane :appcenter_release do
    gradle(task: "clean assembleRelease")
    appcenter_upload(
      api_token: "94834b2e5d4a64c279e421b07f33b32c7b56ca76",
      owner_name: "ajamthe",
      app_name: "Auth0Demo-Android",
      file: '/Users/ashish/dev/auth0/auth0-mobile/android/app/build/outputs/apk/release/app-release.apk'
)

 end

end
